import { createServer } from 'node:http';
// @ts-expect-error -- generated by `vite build`, not present until then
import { handler } from './build/handler.js';
import { handleUpgrade } from './src/lib/server/ws/socket';

const port = Number(process.env.PORT ?? 3000);
const host = process.env.HOST ?? '0.0.0.0';

const server = createServer(handler);

server.on('upgrade', (request, socket, head) => {
  if (!handleUpgrade(request, socket, head)) {
    socket.destroy();
  }
});

server.listen(port, host, () => {
  console.log(`Listening on ${host}:${port}`);
});

process.on('SIGTERM', () => server.close());
process.on('SIGINT', () => server.close());
