import { faker } from '@faker-js/faker';
import { config as envConfig } from 'dotenv';
import { defineRelations } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/mysql2';
import { reset, seed } from 'drizzle-seed';
import { createPool } from 'mysql2';
import * as schema from './schema';
import {
  config,
  game,
  gameEdition,
  gameTranslation,
  gameTranslationFile,
  gameTranslationTranslator,
  originWebsite,
  role,
  translator,
  translatorLink,
  user,
} from './schema';

envConfig();

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL is not set');
}

const relations = defineRelations(schema);

//? See src/lib/server/db/index.ts for why the client is created explicitly instead of passing the URL directly.
const client = createPool(process.env.DATABASE_URL);

const db = drizzle({ client, relations });

export const main = async () => {
  await reset(db, schema);

  await seed(db, {
    originWebsite,
    game,
    gameEdition,
    gameTranslation,
    gameTranslationFile,
    translator,
    translatorLink,
    role,
    config,
    user,
  }).refine((funcs) => ({
    game: {
      columns: {
        threadId: funcs.int({ minValue: 0, maxValue: 16_777_215 }),
        name: funcs.valuesFromArray({
          values: Array.from({ length: 50 }, () =>
            faker.commerce.productName(),
          ),
        }),
        imageExternal: funcs.valuesFromArray({
          values: Array.from({ length: 50 }, () =>
            faker.image.personPortrait(),
          ),
        }),
      },
    },
    gameEdition: {
      columns: {
        name: funcs.valuesFromArray({
          values: Array.from({ length: 50 }, () =>
            faker.commerce.productName(),
          ),
        }),
      },
    },
    translator: {
      columns: {
        name: funcs.valuesFromArray({
          values: Array.from({ length: 50 }, () => faker.person.fullName()),
        }),
      },
    },
    translatorLink: {
      columns: {
        name: funcs.valuesFromArray({
          values: Array.from({ length: 50 }, () => faker.internet.domainWord()),
        }),
        order: funcs.int({ minValue: 0, maxValue: 255 }),
      },
    },
    role: {
      count: 5,
      columns: {
        name: funcs.valuesFromArray({
          values: ['user', 'author', 'translator', 'moderator', 'admin'],
          isUnique: true,
        }),
        label: funcs.valuesFromArray({
          values: [
            'Utilisateur',
            'Auteur',
            'Traducteur',
            'Modérateur',
            'Admin',
          ],
          isUnique: true,
        }),
      },
    },
    config: {
      count: 1,
      columns: {
        name: funcs.valuesFromArray({
          values: ['F95 France'],
        }),
      },
    },
    gameTranslation: {
      columns: {
        type: funcs.valuesFromArray({
          values: [
            'no_translation',
            'integrated',
            'translation',
            'translation_with_mods',
            'mods',
          ],
        }),
      },
    },
  }));

  // drizzle-seed picks FK pairs independently and doesn't know about this table's composite PK,
  // so duplicate (gameTranslationId, translatorId) pairs are near-guaranteed — generated by hand instead.
  const gameTranslations = await db
    .select({ id: gameTranslation.id })
    .from(gameTranslation);
  const translators = await db.select({ id: translator.id }).from(translator);

  const pairs = new Set<string>();
  const links: (typeof gameTranslationTranslator.$inferInsert)[] = [];
  const maxLinks = Math.min(10, gameTranslations.length * translators.length);

  while (links.length < maxLinks) {
    const gt = faker.helpers.arrayElement(gameTranslations);
    const t = faker.helpers.arrayElement(translators);
    const key = `${gt.id}-${t.id}`;

    if (pairs.has(key)) continue;
    pairs.add(key);

    links.push({
      gameTranslationId: gt.id,
      translatorId: t.id,
      alert: faker.datatype.boolean(),
      type: faker.helpers.arrayElement(['translator', 'proofreader']),
    });
  }

  await db.insert(gameTranslationTranslator).values(links);
};

if (import.meta.main) {
  await main();
  process.exit(0);
}
