import { Migration } from '@mikro-orm/migrations';

//? Renseigne `game_tags.f95_id` : correspondance id F95Checker → nom du tag, reprise de l'enum `Tag`
//? de F95Checker (common/structs.py, GPLv3). Un tag déjà présent (même nom, sans tenir compte de la
//? casse) reçoit l'id, sur sa ligne la plus ancienne car `f95_id` est unique ; un tag absent est créé.
//? Les tags de la v4 sans équivalent chez F95 gardent un `f95_id` nul.
const F95_TAGS: [id: number, name: string][] = [
  [1, '2d game'],
  [2, '2dcg'],
  [3, '3d game'],
  [4, '3dcg'],
  [5, 'adventure'],
  [6, 'ahegao'],
  [7, 'anal sex'],
  [8, 'animated'],
  [9, 'asset-addon'],
  [10, 'asset-ai-shoujo'],
  [11, 'asset-animal'],
  [12, 'asset-animation'],
  [13, 'asset-audio'],
  [14, 'asset-bundle'],
  [15, 'asset-character'],
  [16, 'asset-clothing'],
  [17, 'asset-environment'],
  [18, 'asset-expression'],
  [19, 'asset-hair'],
  [20, 'asset-hdri'],
  [21, 'asset-honey-select'],
  [22, 'asset-honey-select2'],
  [23, 'asset-koikatu'],
  [24, 'asset-light'],
  [25, 'asset-morph'],
  [26, 'asset-plugin'],
  [27, 'asset-pose'],
  [28, 'asset-prop'],
  [29, 'asset-script'],
  [30, 'asset-shader'],
  [31, 'asset-texture'],
  [32, 'asset-utility'],
  [33, 'asset-vehicle'],
  [34, 'bdsm'],
  [35, 'bestiality'],
  [36, 'big ass'],
  [37, 'big tits'],
  [38, 'blackmail'],
  [39, 'bukkake'],
  [40, 'censored'],
  [41, 'character creation'],
  [42, 'cheating'],
  [43, 'combat'],
  [44, 'corruption'],
  [45, 'cosplay'],
  [46, 'creampie'],
  [47, 'dating sim'],
  [48, 'dilf'],
  [49, 'drugs'],
  [50, 'dystopian setting'],
  [51, 'exhibitionism'],
  [52, 'fantasy'],
  [53, 'female domination'],
  [54, 'female protagonist'],
  [55, 'footjob'],
  [56, 'furry'],
  [57, 'futa/trans'],
  [58, 'futa/trans protagonist'],
  [59, 'gay'],
  [60, 'graphic violence'],
  [61, 'groping'],
  [62, 'group sex'],
  [63, 'handjob'],
  [64, 'harem'],
  [65, 'horror'],
  [66, 'humiliation'],
  [67, 'humor'],
  [68, 'incest'],
  [69, 'internal view'],
  [70, 'interracial'],
  [71, 'japanese game'],
  [72, 'kinetic novel'],
  [73, 'lactation'],
  [74, 'lesbian'],
  [75, 'loli'],
  [76, 'male domination'],
  [77, 'male protagonist'],
  [78, 'management'],
  [79, 'masturbation'],
  [80, 'milf'],
  [81, 'mind control'],
  [82, 'mobile game'],
  [83, 'monster'],
  [84, 'monster girl'],
  [85, 'multiple endings'],
  [86, 'multiple penetration'],
  [87, 'multiple protagonist'],
  [88, 'necrophilia'],
  [89, 'no sexual content'],
  [90, 'netorare'],
  [91, 'oral sex'],
  [92, 'paranormal'],
  [93, 'parody'],
  [94, 'platformer'],
  [95, 'point & click'],
  [96, 'possession'],
  [97, 'pov'],
  [98, 'pregnancy'],
  [99, 'prostitution'],
  [100, 'puzzle'],
  [101, 'rape'],
  [102, 'real porn'],
  [103, 'religion'],
  [104, 'romance'],
  [105, 'rpg'],
  [106, 'sandbox'],
  [107, 'scat'],
  [108, 'school setting'],
  [109, 'sci-fi'],
  [110, 'sex toys'],
  [111, 'sexual harassment'],
  [112, 'shooter'],
  [113, 'shota'],
  [114, 'side-scroller'],
  [115, 'simulator'],
  [116, 'sissification'],
  [117, 'slave'],
  [118, 'sleep sex'],
  [119, 'spanking'],
  [120, 'strategy'],
  [121, 'stripping'],
  [122, 'superpowers'],
  [123, 'swinging'],
  [124, 'teasing'],
  [125, 'tentacles'],
  [126, 'text based'],
  [127, 'titfuck'],
  [128, 'trainer'],
  [129, 'transformation'],
  [130, 'trap'],
  [131, 'turn based combat'],
  [132, 'twins'],
  [133, 'urination'],
  [134, 'vaginal sex'],
  [135, 'virgin'],
  [136, 'virtual reality'],
  [137, 'voiced'],
  [138, 'vore'],
  [139, 'voyeurism'],
  [140, 'ai cg'],
  [141, 'asset-daz-gen2'],
  [142, 'asset-daz-gen3'],
  [143, 'asset-daz-gen8'],
  [144, 'asset-daz-gen81'],
  [145, 'asset-daz-gen9'],
  [146, 'asset-female'],
  [147, 'asset-male'],
  [148, 'asset-nonbinary'],
  [149, 'asset-scene'],
  [150, 'asset-playhome'],
  [151, 'asset-daz-gen1'],
  [152, 'asset-daz-m4'],
  [153, 'asset-daz-v4'],
  [154, 'unknown'],
];

export class Migration20260921150000_fill_game_tags_f95_id extends Migration {
  override name = 'Migration20260921150000_fill_game_tags_f95_id';

  override async up(): Promise<void> {
    for (const [id, name] of F95_TAGS) {
      await this.execute(
        'update `game_tags` set `f95_id` = ? where `id` = (select `id` from (select min(`id`) as `id` from `game_tags` where `name` = ?) as `oldest`) and `f95_id` is null',
        [id, name],
      );
      await this.execute(
        'insert into `game_tags` (`name`, `f95_id`) select ?, ? from dual where not exists (select 1 from `game_tags` where `name` = ?)',
        [name, id, name],
      );
    }
  }

  //? Les tags créés par `up` restent : rien ne les distingue d'un tag ajouté ensuite à la main.
  override async down(): Promise<void> {
    await this.execute('update `game_tags` set `f95_id` = null');
  }
}
